# Generated by Django 4.0.6 on 2022-11-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default="2022-01-01"),
            preserve_default=False,
        ),
    ]
