# Generated by Django 4.0.6 on 2022-12-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=11)),
                ('desc', models.CharField(max_length=300)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
